### ISSUE TITLE
Extracting NT Security details and directory extraction

### ISSUE THREAD

**Issue by balajir712** [josemesona/ManagedWimgApi#14]
Hi,

   Thanks for providing the wrapper c# code for WIMGAPI. Could you let me know if its possible to extract the NT Security details for files and directories from the WIM File with this c# wrapper class? If so, Kindly provide some code samples.

  Also, is it possible to extract directories instead of just files from WIM file using this C# API ?

Thanks,
Balaji R

**Comment by josemesona** [comment]
> Could you let me know if its possible to extract the NT Security details for files and directories from the WIM File with this c# wrapper class?

I am not sure if WIMGAPI stores ACLs of the files within the `.wim` file.  This managed wrapper only supports what the native API can do.  I did some quick research and I don't see anything related to this.

> is it possible to extract directories instead of just files from WIM file using this C# API

You could [registry a callback](https://github.com/josemesona/ManagedWimgApi/blob/a736f6c23d6a4e3495136a9d049c39330f6e35fe/src/Microsoft.Wim/WimgApi.cs#L893) before calling [ApplyImage](https://github.com/josemesona/ManagedWimgApi/blob/a736f6c23d6a4e3495136a9d049c39330f6e35fe/src/Microsoft.Wim/WimgApi.cs#L40) and then filter out files you don't want to extract.

Your callback would receive a `WimMessageType.Process` which you would cancel if you didn't want it applied.  There's a similar sample [here](https://msdn.microsoft.com/en-us/library/windows/desktop/dd851944.aspx).
