### ISSUE TITLE
Exclude file

### ISSUE THREAD

**Issue by Arclight05** [josemesona/ManagedWimgApi#15]
Hi, 
Is it possible to exclude some file from CaptureImage ?
like :
 C:\System Volume Information
 hiberfil.sys
 ...
It's look like possible on the native C++ API via callback process.
Cordialy,

**Comment by josemesona** [comment]
Yes, you would need to register a callback which receives a `WimMessageType.Process` which you can cancel if you want it left out of the capture. 

You can find a sample of registering a callback in the unit test [CaptureImageWithCallbackTest](https://github.com/josemesona/ManagedWimgApi/blob/ebadf7353748bed2324fa8e61b2198a1799c082d/src/Microsoft.Wim.Tests/CaptureImageTests.cs#L58)

And there's a native sample here as well: https://msdn.microsoft.com/en-us/library/windows/desktop/dd834943.aspx
