### ISSUE TITLE
WimMessageScanning parameters are incorrect

### ISSUE THREAD

**Issue by Herohtar** [josemesona/ManagedWimgApi#17]
After working with the WimgApi and trying to use the WimMessageScanning callback message, I discovered that its behavior is incorrect, but it's actually a problem with the API differing from the Microsoft documentation.

Currently, the `WimMessageScanning` object has `DirectoryCount` and `FileCount` properties, in line with the documentation which says that `lParam` specifies the number of files scanned and `wParam` is the number of directories scanned. However, that is not true; `lParam` will contain *either* the total number of files scanned OR the total number of directories scanned, and `wParam` is a flag to show which -- if `wParam == 0` then `lParam` contains the total number of files, if `wParam == 1` then `lParam` contains the total number of directories.

**Comment by josemesona** [comment]
You are totally right.  The documentation is wrong but under the debugger I can clearly see that `wParam` indicates if its a directory or file count.

I'll send a PR to fix this...

**Comment by josemesona** [comment]
@Herohtar please review #23 and let me know what you think.

**Comment by Herohtar** [comment]
That will work, but having two properties seems unnecessary since it's just a Boolean -- if one is true you know the other has to be false. I would suggest either having just `IsDirectoryCount`, since that is typically the less common case, or else give it an enum property something like `CountType` with values of `File` and `Directory`.

**Comment by josemesona** [comment]
The fix is available in 1.2.3: https://www.nuget.org/packages/Microsoft.Wim/1.2.3
