### ISSUE TITLE
ESD Support

### ISSUE THREAD

**Issue by josemesona** [josemesona/ManagedWimgApi#2]
Get the image count for an ESD file returns 0.

**Comment by MichalPavlik** [comment]
Hi,
did you try to use value 0x20000000 as _options_ parameter in _CreateFile_? Without this undocumented value, I wasn't able to even obtain WIM handle. _GetImageCount_ is working but I tried only one ESD so far. Hope it helps.

**Comment by josemesona** [comment]
I haven't tried that yet, how do you know about that option?  I'm a little weary about using anything undocumented but if it's the only way to get ESD support through the WIMGAPI, then let's add it.

**Comment by MichalPavlik** [comment]
It was mentioned in this forum: http://theoven.org/index.php?topic=1596.0

Using _WimCreateFileOptions.None_ leads to exception (in my case), but passing that value seems to be working. Just try it and you will see :)
