### ISSUE TITLE
Create new ESD file

### ISSUE THREAD

**Issue by FanIT** [josemesona/ManagedWimgApi#3]
Hello. I'm trying to create new ESD file. But i get exception "the parameter is incorrect".
My code:
`WimHandle newHandle = WimgApi.CreateFile(@"E:\install.esd", WimFileAccess.Write,
                WimCreationDisposition.CreateAlways, WimCreateFileOptions.ShareWrite, WimCompressionType.Lzms);`

**Comment by josemesona** [comment]
This error is coming from the native implementation of the WimCreateFile function in WimgApi.dll.  I'm not entirely sure why but it appears that the WimCompressionType of Lzms might have been deprecated in Windows 10.  I don't see it in the [documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/dd851934.aspx) an more.  Can you try specifying a different compression type and see if that works?

Also, if it doesn't, please let me know more details about what version of Windows you're on and any related info.

**Comment by FanIT** [comment]
I was trying in windows 8.1. Afterward i have installed windows ADK 10, but the error appear again.
Others compression type work fine.

**Comment by josemesona** [comment]
Since Lzms compression isn't listed in the documentation, you should just use None, Xpress, or Lzx.  I think I included this Lzms value because it is in Wimgapi.h.

**Comment by josemesona** [comment]
Should I close out this issue or do you want to dig a little deeper into why this compression level isn't available for ESD?

**Comment by FanIT** [comment]
Yes. You can close this issue. I trying to write wrapper over wimlib.

**Comment by josemesona** [comment]
Okay sorry I couldn't help more.  Hopefully someone knows why certain compression levels aren't available.
